title = "PADLOCK"
baseURL = "http://localhost"
theme = "ananke"
resourceDir = "../resources"

SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "A highly scalable and decentralized blockchain"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/padlock-xpl"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/bigpic.jpg"
  recent_posts_number = 2
